Jenkinsfile
package.json

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Add Jenkinsfile contents and update package.json

---

Jenkinsfile

Do not merge until TPSRs are completed.
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Wait to Merge: Create zowe-v1-lts version of the SCS plugin.

---

CHANGELOG.md
CONTRIBUTING.md

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Update the changelog

---

CHANGELOG.md

Merging this PR does not require a version bump.

Update changelog for v4.0.2

---

README.md

Add detailed install requirements for Linux

---

CHANGELOG.md

Edit the most recent changelog entries for Zowe 1.15.0. 
Release Notes will be automatically generated from all Changelog files.

edit changelog

---

CHANGELOG.md
Jenkinsfile
jenkins/bundleKeytar.sh
package.json
src/cli/IProfileData.ts

Update Keytar to v6.0.1

---

CHANGELOG.md

Giving the most recent update a PR # so that it's consistent w/ other entries. 
Signed-off-by: Brandon Jenkins <36675406+BrandonJenkins14@users.noreply.github.com>

Minor changelog update

---

CHANGELOG.md

Fix release notes for v4.1.1

---

CHANGELOG.md
README.md

Add note to readme for npm@7 users

---

CHANGELOG.md
Jenkinsfile
package.json

Update Keytar to v7.1.0

---

Jenkinsfile

See https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/cli/zowe-cli-prebuilds/

Upload Keytar prebuilds to Artifactory

---

.npmrc

Update registry in npmrc to use https

---

CHANGELOG.md
README.md

Signed-off-by: JamesBauman <james.bauman@broadcom.com>

updated SWR for the plug-in to include npm@7 and npm@8

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Fix potential vulnerability in transitive dep minimist

---

README.md

Update readme to mention Zowe v2 status

---

CHANGELOG.md
npm-shrinkwrap.json

**What It Does**
Updates the semver dependency
**How to Test**
Look at the changed files?
**Review Checklist**
I certify that I have:
**Additional Comments**

Update semver dependency

---

.github/workflows/zowe-cli-plugin.yml

**What It Does**
Update CI to use Node 18 and 20
**How to Test**
**Review Checklist**
I certify that I have:
**Additional Comments**

Update node versions for CI

---

CHANGELOG.md
package.json

**What It Does**
**How to Test**
**Review Checklist**
I certify that I have:
**Additional Comments**

Add missing shrinkwrap

---

.github/workflows/audit.yml

**What It Does**
Enable nightly audit cron so we can have a working audit badge
**How to Test**
**Review Checklist**
I certify that I have:
**Additional Comments**

Enable nightly audit check
